-- Round-trip fixture for Postgres dumps (crates/dbcore/tests/dump_postgres.rs), loaded into a
-- scratch database: types, sequences, identity/generated columns, partitions, inheritance,
-- views on views, a materialized view, functions (incl. one returning a table's rows and a
-- BEGIN ATOMIC body), a trigger, row security, comments and awkward values.

create extension if not exists pgcrypto;
create schema shop;
create schema "we""ird";

create type shop.mood as enum ('sad', 'ok', 'happy', 'it''s complicated');
create domain shop.positive as numeric(10, 2) constraint positive_check check (value > 0);
create type shop.address as (street text, zip varchar(10));
create type shop.floatrange as range (subtype = float8);
create sequence shop.ticket_seq start 100 increment 5;

create function shop.slugify(t text) returns text language sql immutable
as $$ select lower(regexp_replace(t, '\W+', '-', 'g')) $$;

create table shop.customers (
  id         bigint generated always as identity primary key,
  email      text not null unique,
  name       text collate "C",
  mood       shop.mood default 'ok',
  address    shop.address,
  tags       text[] default '{}',
  slug       text generated always as (shop.slugify(name)) stored,
  created    timestamptz default now(),
  balance    shop.positive,
  ratio      float8,
  meta       jsonb,
  photo      bytea,
  ticket     int default nextval('shop.ticket_seq'),
  constraint email_has_at check (email like '%@%')
);
comment on table shop.customers is 'People who buy';
comment on column shop.customers.email is 'Login; unique';

create table shop.orders (
  id           serial primary key,
  customer_id  bigint not null references shop.customers (id) on delete cascade,
  total        numeric(12, 2) not null,
  placed_on    date not null,
  during       tstzrange,
  span         shop.floatrange,
  note         text
);
create index orders_customer on shop.orders (customer_id);
create index orders_note_lower on shop.orders (lower(note)) where note is not null;

create table shop.events (
  id       bigint generated by default as identity,
  at       date not null,
  payload  jsonb
) partition by range (at);
create table shop.events_2024 partition of shop.events for values from ('2024-01-01') to ('2025-01-01');
create table shop.events_2025 partition of shop.events for values from ('2025-01-01') to ('2026-01-01');
alter table shop.events add primary key (id, at);
create index events_payload on shop.events using gin (payload);

create table "we""ird"."Mixed Case" ("Id" int primary key, "semi;colon" text, "back\slash" text);
create unlogged table shop.cache (k text primary key, v text) with (fillfactor = 70);
create table shop.base (id int, label text);
create table shop.derived (extra int) inherits (shop.base);

create function shop.recent(n int) returns setof shop.orders language sql
as $$ select * from shop.orders order by id desc limit n $$;
create function shop.atomic_total() returns numeric language sql
begin atomic
  select coalesce(sum(total), 0) from shop.orders;
end;
create function shop.touch() returns trigger language plpgsql as $$
begin
  new.note := coalesce(new.note, 'auto; touched');
  return new;
end
$$;
comment on function shop.touch() is 'Fills in notes';
create procedure shop.noop() language plpgsql as $$ begin null; end $$;
create trigger orders_touch before insert on shop.orders for each row execute function shop.touch();

create view shop.order_totals as
  select c.email, sum(o.total) as total from shop.customers c join shop.orders o on o.customer_id = c.id group by c.email;
create view shop.big_spenders as select * from shop.order_totals where total > 100;
create materialized view shop.mood_counts as select mood, count(*) as n from shop.customers group by mood;
create unique index mood_counts_mood on shop.mood_counts (mood);

alter table shop.orders enable row level security;
create policy positive_orders on shop.orders for select using (total > 0);

insert into shop.customers (email, name, mood, address, tags, balance, ratio, meta, photo) values
  ('a@x.io', 'Ann O''Neil', 'happy', row('Main St 1', '1000'), '{a,"b c"}', 10.5, 0.1, '{"k": [1, 2, {"z": null}]}', '\x00ff0a5c'),
  ('b@x.io', E'tab\there\nnewline \\ back \\.', 'sad', null, '{}', 1, 'NaN', null, ''),
  ('c@x.io', 'üñí 🐻', 'it''s complicated', null, null, null, '-Infinity', '"str"', null),
  ('d@x.io', null, null, null, '{NULL}', null, 1e-300, null, null);
insert into shop.orders (customer_id, total, placed_on, during, span, note)
  select 1 + i % 3, i * 1.25, date '2024-01-01' + i, tstzrange('2024-01-01', null), '[1.5,2.5)', case when i % 2 = 0 then 'n' || i end
  from generate_series(1, 500) i;
insert into shop.events (at, payload) select date '2024-06-01' + i, jsonb_build_object('i', i) from generate_series(1, 400) i;
insert into "we""ird"."Mixed Case" values (1, 'a;b', 'c\d'), (2, null, E'\\.'), (3, E'line\n\\.\nend', '');
insert into shop.cache values ('k', 'v');
insert into shop.base values (1, 'base');
insert into shop.derived values (2, 'derived', 7);
select setval('shop.ticket_seq', 500);
refresh materialized view shop.mood_counts;
